name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        playwright install-deps
    
    - name: Run tests with marker
      run: |
        pytest tests/ -v -m "not slow" --headed=false
    
    - name: Run slow tests
      run: |
        pytest tests/ -v -m "slow" --headed=false
      continue-on-error: true